version: "3.8"

services:

  nginx:
    container_name: vue.task.nginx
    image: nginx:latest
    build: './nginx/'
    ports:
      - "80:80"
    links:
      - php
      - mysql
#    networks:
#      - task-dev
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./www/html:/var/www/html
    restart: unless-stopped

  php:
    container_name: vue.task.php
    image: php:8.0-fpm
    build: './php/'
    expose:
       - 9000
    links:
       - mysql
#    networks:
#      - task-dev
    volumes:
      - ./www/html:/var/www/html
    restart: unless-stopped

  node:
    image: node:19-alpine3.16
    container_name: vue.task.node
    build: "./node/"
    working_dir: /var/www/html
    tty: true
    volumes:
      - ./www/html:/var/www/html
    ports:
      - ${EXTERNAL_NODE_PORT:-5173}:5173
#    networks:
#      - task-dev
    restart: unless-stopped

  mysql:
    container_name: vue.task.mysql
    build: './mysql/'
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./www/html:/var/www/html
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=pwd
      - MYSQL_USER=usr
      - MYSQL_PASSWORD=pwd
#    networks:
#      - task-dev    
    restart: unless-stopped

#networks:
#  task-dev:
#    driver: bridge
